quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none
  smallrye-openapi:
    info-title: system-value-mapping-api
    info-version: 1.1.0
  swagger-ui:
    always-include: true
    operations-sorter: method

##########
'%dev':
  quarkus:
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata
    hibernate-orm:
      log:
        sql: true
    keycloak:
      devservices:
        users:
          admin: Pass123!
        roles:
          admin: SVM_SYSTEM_READ,SVM_SYSTEM_WRITE
    log:
      level: INFO
      category:
        "com.deltaecholabs.svm":
          level: DEBUG

##########
'%test':
  quarkus:
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata
    hibernate-orm:
      log:
        sql: true
    keycloak:
      devservices:
        users:
          admin: Pass123!
        roles:
          admin: SVM_SYSTEM_READ,SVM_SYSTEM_WRITE
    log:
      level: INFO
      category:
        "com.deltaecholabs.svm":
          level: DEBUG

##########
'%prod':
  quarkus:
    flyway:
      migrate-at-start: true
      locations: db/migration
    hibernate-orm:
      log:
        sql: false
    log:
      level: INFO
      category:
        "com.deltaecholabs.svm":
          level: INFO